### ISSUE TITLE
Testing Checklist

### ISSUE THREAD

**Issue by AgnellusX1** [AgnellusX1/GodsEye#34]
Deadline 14-05-2021

- [ ] Headpose --- @AgnellusX1 
- [x] Admin Login --- @clarice99 
- [x] Validate Photo Capture --- @sancia15 
- [x] Results Dropdown --- @clarice99 
- [x] Check for Different Browsers --- @sancia15 
- [x] Firefox Bugs --- @AgnellusX1 
- [x] Cheat Score Errors
- [x] Timer Reset on Full Screen Alert --- @AgnellusX1  6fedcab70bb65b69bb5e7673eaac7fdc519c2880
- [x] Cleanup
